openapi: 3.0.3
info:
  title: Transaction Enrichment
  version: 1.0.0
servers:
  - url: https://api.richest.com
tags:
  - name: Authentication
  - name: Enrichment
paths:
  /v1/oauth/token:
    post:
      operationId: oauth_token_post
      summary: Get an authentication token for the platform
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/OAuthTokenRequest"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OAuthTokenResponse"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: "Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /v1/enriched-transactions:
    post:
      summary: Enrich a set of transactions
      operationId: enriched_transactions_post
      tags:
        - Enrichment
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnrichTransactionsRequest"
      responses:
        "200":
          description: "Transactions enriched"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnrichTransactionsResponse"
        "400":
          description: "Bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: "Not authorised"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: "Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    OAuthTokenRequest:
      required:
        - client_id
        - client_secret
      properties:
        client_id:
          type: string
        client_secret:
          type: string

    OAuthTokenResponse:
      required:
        - access_token
        - expires_in
      properties:
        access_token:
          type: string
        expires_in:
          type: number

    EnrichTransactionsRequest:
      required:
        - enrichments
        - transactions
      properties:
        enrichments:
          type: array
          items:
            $ref: "#/components/schemas/Enrichments"
        transactions:
          type: array
          items:
            $ref: "#/components/schemas/TransactionForEnrichment"

    TransactionForEnrichment:
      required:
        - id
        - date
        - amount
        - description
      properties:
        id:
          type: string
          description: "Unique ID of the transaction"
        date:
          type: number
          description: "Unix timestamp"
        amount:
          type: number
        description:
          type: string

    EnrichTransactionsResponse:
      type: array
      items:
        $ref: "#/components/schemas/EnrichedTransaction"

    EnrichedTransaction:
      allOf:
        - $ref: "#/components/schemas/TransactionForEnrichment"
        - required:
            - category
            - merchant
            - regularity
          properties:
            category:
              type: string
              nullable: true
              description: "Category derived (if categorisation enrichment chosen)"
            merchant:
              type: string
              description: "Merchant derived (if merchant-identification enrichment chosen)"
            regularity:
              type: string
              description: "Regularity derived (if regularity enrichment chosen)"
    Enrichments:
      type: string
      enum:
        - "categorisation"
        - "merchant-identification"
        - "regularity"


    ErrorResponse:
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - authentication_error
            - validation_error
            - server_error
        message:
          type: string
